### ISSUE TITLE
Search messages not visible in main window

### ISSUE THREAD

**Issue by oltolm** [hltj/wxMEdit#101]
When you use the search dialog you get messages like "Cannot find the matched string" (should probably be "Can not"), but the messages are only displayed in the search dialog. When you close the search dialog and press `F3` then you don't see any messages. This makes it hard to use the search.

Please display the messages not in the search dialog, but in the main window.

**Comment by hltj** [comment]
Notepad++ does not show the message either. Change the label to feature.
