### ISSUE TITLE
Spaces were shown as tabs with "Show Space Char" off & "Show Tab Char" on

### ISSUE THREAD

**Issue by oltolm** [hltj/wxMEdit#105]
I tested wxMEdit v2.9.9.2 on Windows 7. When I turn on "Show Tab Char" wxMEdit shows tabs everywhere, even in places where there is a space. "Show Space Char" works correctly. If I also turn on "Show Space Char" then wxMEdit shows tabs and spaces correctly.

**Comment by hltj** [comment]
original title: "Show Tab Char" doesn't work
