### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by nerijus** [hltj/wxMEdit#112]
2.9.9.3 fails to compile on Fedora 21:
```
src/wxm/wxmedit-searcher.o: In function `operator|':
/usr/include/boost/xpressive/regex_constants.hpp:249: undefined reference to `wxm::g_regex_dot_match_newline'
collect2: error: ld returned 1 exit status
```
$ rpm -qf /usr/include/boost/xpressive/regex_constants.hpp
boost-devel-1.55.0-8.fc21.x86_64

**Comment by hltj** [comment]
Fixed and the download links in official site updated.
