### ISSUE TITLE
Cannot uncompress wxMEdit-2.9.9.3-win32-bin.7z

### ISSUE THREAD

**Issue by RuralHunter** [hltj/wxMEdit#113]
maybe the package problem.
压缩文件有问题。

**Comment by hltj** [comment]
original title: 最新版2.9.9.3 windows版下载后无法解压
original text: 压缩文件有问题。

**Comment by hltj** [comment]
NO. The package has no problem.
Make sure your downloaded package was unbroken.
It has 9,715,287 bytes and the md5sum is:
7a2a9bb4abad9ee31461144fe77a7fd1 *wxMEdit-2.9.9.3-win32-bin.7z

不。压缩包没问题。
请确保你下载的文件是完整的，有 9,715,287 字节，其 md5sum 是：
7a2a9bb4abad9ee31461144fe77a7fd1 *wxMEdit-2.9.9.3-win32-bin.7z
