### ISSUE TITLE
Hardcoded icon path in launcher for GNU/Linux systems

### ISSUE THREAD

**Issue by palob** [hltj/wxMEdit#120]
Hi,

currently the icon path specified in the created .desktop launcher file is set to:
[Icon=@pixmapsdir@/wxmedit.png](https://github.com/hltj/wxMEdit/blob/bf0160bb0644d7f402e174a7bf203a35b2604b8e/wxmedit.desktop._#L9).

This prevents icon theming without editing the launcher file.

The icon is installed to [pixmapsdir = $(datadir)/pixmaps](https://github.com/hltj/wxMEdit/blob/74a81c40eaa478d1b1c15ab01f57aa50bfc624a6/Makefile.am#L159) [cf. here](https://github.com/hltj/wxMEdit/blob/74a81c40eaa478d1b1c15ab01f57aa50bfc624a6/Makefile.in#L1877), i.e. `/usr/share/pixmaps` or `~/.local/share/pixmaps` effectively.

According to the resources linked below `freedesktop.org` standard icon locations are:
`/usr/share/icons/hicolor/[size]/apps/[icon name]`
`~/.local/share/icons/hicolor/[size]/apps/[icon name]`
`/usr/share/pixmaps/[icon name]`

http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

So you install the icon to a standard location already. According to the `freedesktop.org` standard and w.r.t. the icon lookup mechanism of all desktop environment the simple Icon line 

**Icon=wxmedit**

 without the full path and without file extension should suffice.

**Comment by hltj** [comment]
Well, I will confirm whether it works under different distributions and non-linux system such as BSD, OpenIndiana etc.

**Comment by hltj** [comment]
Unfortunately, There is no environment variable $XDG_DATA_DIRS set.
Thus, if install with prefix=/usr/local, the desktop can not find the icon if not using absolute path.

**Comment by stefanhusmann** [comment]
IMHO this is a bug in OpenIndiana. They should set $XDG_DATA_DIRS.
