### ISSUE TITLE
Broken Numpad input under Debian 8

### ISSUE THREAD

**Issue by vehona** [hltj/wxMEdit#124]
If you try to input data using Numpad, instead of numbers you will get "weird" characters, like **ŅņŇňŉŊŋŌōńƅƄƆƃƈ**. Printed characters depend on the button and enabled/disabled Numlock.

**OS**: Debian 8 Jessie
**Release**: wxmedit_3.0.2-2_amd64-wx3-icu52

**Comment by hltj** [comment]
original title: Broken Numpad input

**Comment by hltj** [comment]
Please update to the 3rd package of 3.0.2: http://downloads.sourceforge.net/project/wxmedit/prerelease/3.0.2/wxmedit_3.0.2-3_amd64-wx3-icu52.deb

**Comment by vehona** [comment]
Seems to work now, thank you.
