### ISSUE TITLE
Ubuntu 15.10 Package: Update dependency on libicu52

### ISSUE THREAD

**Issue by AButenko** [hltj/wxMEdit#131]
The Debian/Ubuntu package currently depends on the libicu52 package. This package is gone in Ubuntu 15.10, being replaced with a new libicu55 package.

Please build separate packages for Ubuntu 15.10 and above, which depend on the new package. Since the old package is complete gone from the archive, the package is currently not installable on this Ubuntu release.

**Comment by hltj** [comment]
OK.

**Comment by hltj** [comment]
Done.
http://wxmedit.github.io/downloads.html

**Comment by dol** [comment]
Thank you for the repackaging for 15.10. I currently use two Ubuntu machines. One running 14.04 and the other 15.10. The package for 14.04 is now gone. 14.04 LTS has support until 2019. Could you please provide a package for 14.04.

**Comment by hltj** [comment]
Well, I will. And 14.04 is not gone, and will come out later.

**Comment by hltj** [comment]
@dol ubuntu 14.04 packages uploaded.

**Comment by AButenko** [comment]
Thanks a lot.
