### ISSUE TITLE
Crashing when pressing OK button in "About wxMEdit" window

### ISSUE THREAD

**Issue by surenenfiajyan** [hltj/wxMEdit#139]
Steps to reproduce:

From menu bar open Help->About wxMEdit...
When I press OK on "About" or "License" tab, the program crashes.

Terminal output is "segmentation fault".

OS:                                  LMDE 2 (Linux Mint Debian Edition) 64 bit
wxMEdit Version:             3.1 (Debian 8/LMDE 2 64 bit)

**Comment by hltj** [comment]
Confirmed. I will fix it after the coming release (3. 2), i.e. it will be fixed at 3.3.
