### ISSUE TITLE
Font setting is not stored

### ISSUE THREAD

**Issue by Makoto-WAT** [hltj/wxMEdit#141]
I am using  wxMEdit v3.1 on Windows7.
By font setting, I set it to size "12" of "Japanese font" .

However,  when I reboot, it will go back to "Courier New 11".
I want to hold the font setting.

**Comment by hltj** [comment]
Sorry for I cannot reproduce it.
While threre is really a bug that font-size always set to "12".

**Comment by Makoto-WAT** [comment]
Thanks for your quick reply.

I send screens of my situation to you.
I set "font and size" in wxMEdit v3.1 on Windows7.
When I restart wxMEdit, my setting is displayed.
wxMEdit1.png
![wxmedit1](https://cloud.githubusercontent.com/assets/18320144/14351161/abfce69c-fd08-11e5-8294-e3bf56a3b557.png)

However, when I read a text file, the font setting is returned to the initial state.
wxMEdit2.png
![wxmedit2](https://cloud.githubusercontent.com/assets/18320144/14351171/bb7ee750-fd08-11e5-8913-0d4b999e4433.png)

**Comment by hltj** [comment]
This may be the same problem as #142 (fixed, will be included in release 3.2).
