### ISSUE TITLE
Font not restored after restart

### ISSUE THREAD

**Issue by plzak** [hltj/wxMEdit#142]
After upgrading to ver. 3.1, it seems wxMEdit is not able to restore the selected font after restart.
If I change the font to another one, it goes back to Monospace after wxMEdit restart.
But it seems that the problem depends also on the used encoding - while I have this problem with UTF-8 files, the font for Windows-1250 files is remembered correctly.

However, looking into the wxmedit.cfg file, it looks the font was stored correctly:
`[Fonts]`
`UTF-8=Liberation Mono`  // restores to Monospace
`Windows-1250=Liberation Mono`  // restores to Liberation Mono
`...`
Also, while trying to figure out what is happening, the encoding itself was not remembered for some of the files. But this might not be related to the above problem, perhaps...

Thanks for your help.

**Comment by hltj** [comment]
Sorry for reply so late...and I will confirm it later.

**Comment by cbjcbj** [comment]
Hi, I use ver 3.1 in ubuntu 14 and find the same problem. Then I edit ~/.wxmedit/wxmedit.cfg, change HexFontName to my favorite one, and it works. Hope this help.

**Comment by plzak** [comment]
cbjcbj: Thanks for the tip. It seems that HexFontName now works as the default font. So it is better than nothing, but the problem is not solved, as the encoding-specific font settings still do not work.
Thanks anyway :)

**Comment by cbjcbj** [comment]
It's my pleasure:)
