### ISSUE TITLE
Request for "Always force encoding"

### ISSUE THREAD

**Issue by muldjord** [hltj/wxMEdit#145]
I have a situation where I need all files to load as "CP850" encoding no matter what is detected. Would you consider implementing such an option? Currently it is possible to choose default encoding for new files and for files where the detection failed. An extra checkbox to "Always force default encoding" would do the trick.

I'd love to make this feature myself, but I have absolutely no idea to set up a compilation environment on Windows, which is where I need it.

Thank you for making this software.

**Comment by muldjord** [comment]
You may strike this issue. I found an alternative solution.

**Comment by hollowaytape** [comment]
I'd also appreciate this feature, as I need to look at files in Shift JIS only. I will attempt to work on a pull request, but I'd like to hear your alternative solution @muldjord if it might help my situation.

**Comment by muldjord** [comment]
@hollowaytape , I simply wrote my own editor. A bit of a drastic solution I guess, but using the Qt framework it was really easy to implement the features for a QTextEdit that I needed. :)

**Comment by hltj** [comment]
I will implemant this feature in the comming release (3.2). The option may be added in the General tab of the option dialog.
