### ISSUE TITLE
Windows - Portable, minor "issue"

### ISSUE THREAD

**Issue by highend** [hltj/wxMEdit#146]
Hi,
wxMEdit is a portable app which I really like. It doesn't write to the registry, puts it's config file into the application dir.

There is one minor issue: It creates a folder named "wxmedit" in %APPDATA% (which resolves to: C:\Users\<your user name>\AppData\Roaming). I see no files in there. Could you stop wxMEdit from creating this folder when it already knows that it will store it's config in it's application folder?

Options - General:
[ ] Place configuration files into application data directory...
is unchecked.

Thanks,
Highend

**Comment by hltj** [comment]
Please confirm runtime user have write privilege to the wxMEdit directory. If not wxMEdit still write to %APPDATA%.

**Comment by hltj** [comment]
It may be created by first time run the option unchecked.

**Comment by highend** [comment]
The folder in %APPDATA% is always created through wxMEdit even when this option is unchecked (I closed wxMEdit, deleted the folder, started it again while [ ] Place configuration... was still unchecked)...

**Comment by hltj** [comment]
OK, confirmed. I will fix it later.

**Comment by highend** [comment]
Ok, thx!
