### ISSUE TITLE
Feature request: show file size in human readable format

### ISSUE THREAD

**Issue by catcat520** [hltj/wxMEdit#147]
功能需求：希望在最底下的状态栏，可以显示当前文件的 KB 大小，方便统计
虽然现在可以显示 字节，建议加多一个 KB 一目了然

---
Feature request: show file size in human readable format.
Currently wxMEdit shows file size in bytes, it's better to show in KB as well.
It will be clear and easy to count.

**Comment by hltj** [comment]
更大的文件可能需要显示MB，该如何处理？

**Comment by catcat520** [comment]
常见php html 之类源文件的 大多是 kb 的，如果达到 MB 显示 MB，达到 GB 显示 GB 也是可以的，不过 经常编辑 GB 级别文件的人应该是很罕见的。

**Comment by hltj** [comment]
我再想想怎么实现

**Comment by catcat520** [comment]
你看这样如何
<img width="925" alt="2016-08-16_222157" src="https://cloud.githubusercontent.com/assets/9632762/17702583/1bbf5794-6401-11e6-8629-de118b4872e2.png">

**Comment by hltj** [comment]
Original title: 功能需求：希望在最底下的状态栏，可以显示当前文件的 KB 大小

**Comment by hltj** [comment]
文件大小的易读格式采用 Windows 风格（当然并不完全相同），例如：
The human readable format of file size use Windows style format (but not the exact same one).  e.g.:

| File size    | The human readable format |
|--------------|---------------------------|
|            1 | 1                         |
|         1023 | 1,023                     |
|         1024 | 1,024 (1.00KiB)           |
|         1044 | 1,044 (1.01KiB)           |
|         1127 | 1,127 (1.10KiB)           |
|        10239 | 10,239 (9.99KiB)          |
|        10240 | 10,240 (10.0KiB)          |
|       102399 | 102,399 (99.9KiB)         |
|       102400 | 102,400 (100KiB)          |
|      1023999 | 1,023,999 (999KiB)        |
|      1024000 | 1,024,000 (0.97MiB)       |
|      1048576 | 1,048,576 (1.00MiB)       |
|     10485760 | 10,485,760 (10.0MiB)      |
|   1048575999 | 1,048,575,999 (999MiB)    |
|   1048576000 | 1,048,576,000 (0.97GiB)   |
|   1073741824 | 1,073,741,824 (1.00GiB)   |
|   1181116007 | 1,181,116,007 (1.10GiB)   |
|  10737418240 | 10,737,418,240 (10.0GiB)  |
| 107374182400 | 107,374,182,400 (100GiB)  |
