### ISSUE TITLE
Crash when reloading files under Linux

### ISSUE THREAD

**Issue by cbjcbj** [hltj/wxMEdit#149]
Hi, I use madedit on Windows and I love it very much. When I am on Ubuntu I find your program and I always use it. However, sometimes I run into a crash and make my computer die down. If I open a file in a wxmedit window, and modify the file by other wxmedit windows or other programs, when I turn back to original wxmedit window, a dialog will pop up, saying this file is modified somewhere, do you want to updata, or something alike. No matter I press Yes or No or I do nothing, whenever the dialog pops up, my computer will stop working. I am on Ubuntu 14.04. I think it may be a bug and hope you have time to fix it.

**Comment by MrColdbird** [comment]
You are misinterpreting what is happening here.
What you are describing is a symptom of bug #89.

This bug should be closed as a duplicate.

**Comment by cbjcbj** [comment]
Thank you!
