### ISSUE TITLE
Compilation under Mac OS X no longer works

### ISSUE THREAD

**Issue by metalman88** [hltj/wxMEdit#150]
As per the comment at the end of https://github.com/hltj/wxMEdit/issues/57 , there's some incompatibility between the current setup of wxWidgets/the install instructions and what's currently available on Mac.

wxGTK 2.8 no longer works due to wSTRING conversions that don't work, but wxGTK 3.0 also doesn't work due to other incompatibilities, making it impossible to compile it on Mac currently.

I have experimented with doing it with wxCocoa, but that would require significant changes as well, due to the nature of how that changes some of the assumptions the GTK 2-style design expects.

Is there any idea as to whether to make it compatible with 2.8 or fix the bugs that block it from being used with 3.0 under Mac's wxGTK3?

**Comment by hltj** [comment]
I will fix build with wxGTK 2.8 under Mac OS X soon.
This issue is closed. Turn to #57 .
