### ISSUE TITLE
Messy code in column mode when pasting under Ubuntu 16

### ISSUE THREAD

**Issue by cbjcbj** [hltj/wxMEdit#151]
I can use colume mode to input by keyboard. However when I use colume mode to copy and paste I get messy code (see attachment). I have this problem when I switch to ubuntu 16.04. I did not have this on ubuntu 14.04 before.
[a.txt](https://github.com/hltj/wxMEdit/files/557912/a.txt)

**Comment by hltj** [comment]
It's not column problem under Ubuntu 16.
The **real** reason is the encoding of the target file you pasted **cannot** support the pasted characters.
Please convert your file to another encoding which support the characters (e.g. UTF-8) before pasting.

**Comment by cbjcbj** [comment]
The file a.txt I uploaded is in UTF-8 encoding. It just containes lines of "hello" and when I try to copy the first colume it fails. Just now I try to use UTF-16LE encoding but the same problem happens. I use Ubuntu Kylin 16.04.
![1](https://cloud.githubusercontent.com/assets/20900795/19846352/77e6e52e-9f79-11e6-8669-f1b3c33abd30.png)

**Comment by hltj** [comment]
OK. I'll confirm it.
我确认下哈。

**Comment by cbjcbj** [comment]
Thank you:) 谢谢^_^

**Comment by hltj** [comment]
New packages coming soon.

**Comment by hltj** [comment]
Packages updated. Please download & reinstall.
