### ISSUE TITLE
Can't detect the correct encoding of the file in win 10

### ISSUE THREAD

**Issue by gituser9527** [hltj/wxMEdit#152]
Windows 10 X64 latest ver
I create a new text file by right clicking on the desktop or other folders, and type some characters with Chinese words, then open it with wxMEdit, it's opened with a wrong encoding, which is 'ISO-8859-2'.
It should be GB18030.
----------
I tried it again, this time it detected it as 'Japnese（日文）'， the software seemed to be confused haha~
-----------
if i insert BOM to a GB18030-UNICODE file, then it worked ok. But if I create whether with 'Microsoft Notepad' or 'wxMEdit', it happened again.

**Comment by gituser9527** [comment]
MS936(GBK) has no 'BOM' option.
GB18030-UNICODE has this BOM Option.
Both of 'MS936' and 'GB18030-unicode' can decode the file with chinese characters right, but it can only detect files encoded with GB18030-UNICODE-with-BOM!
so it seemed the encodeing-detect-module doesn't work well!

**Comment by hltj** [comment]
Encoding detection is **not absolutely precise**, and it's **impossible**.
It is statistical-based detection. Thus, too few characters can not detected exactly.

编码识别**不是也不可能是**绝对精确的。
它是基于统计的识别。所以特别少的字符难以识别准确。

**Comment by gituser9527** [comment]
wow!
原来如此！测试了一下，果然是！
tested, it is!
thank you so much!
-----------------------
P.S
looking for a perfect text editor,yeas ago found madedit at last.
there are 2 kinds of editors on this planet, one is madedit, the others are not.
