### ISSUE TITLE
Crash in text mode when a line exceed the limit of line length (with default value 4096)

### ISSUE THREAD

**Issue by noisnemid** [hltj/wxMEdit#153]
在.SQL文件中，经常遇到单行很长的文件（比如单行INSERT可能会超过几百KiBytes）。文件中超过多个这样的400KB左右长行时，且关闭自动换行，稍微滚动两下，程序便处于失去响应状态。这种情况是在我尝试使用查找功能时发现的。如果行再长一点，如果超过1MB，在打开自动换行的情况下是OK的；一旦尝试关闭自动换行，程序有时会立即崩溃，即使不，也会失去响应。在有长行时，滚动视图，CPU占用会急速上升。您可尝试生成更多类似极端数据进行测试。
----------------
a '.sql' file with more than 1 ultra-long-single-lines, 'auto-word wrap' option off, then the software got problems and it loses response.
please confirm this. 
sql files with super long lines are very common when they are dumped automacically by 'mysql'.
in old days, this is the only principle by which i chose a text editor, i tested many text-editors, only about 2 or 3 softs could edit super-long lines very well, and madedit was one of them, while now , it encountered the same problem.
----------
[loooon-line-sample.zip](https://github.com/hltj/wxMEdit/files/609168/loooon-line-sample.zip)

sample files attached

**Comment by RuralHunter** [comment]
是的，遇到很长的行就会挂掉。

**Comment by hltj** [comment]
Original Titile: ultra-long-single-line got problem!
