### ISSUE TITLE
updated icu-58.1.2 error while loding shared libraries:libicui18n.so.57

### ISSUE THREAD

**Issue by fanicy** [hltj/wxMEdit#155]
Archlinux 
When I update icu from icu-57.1 to icu 58.1.2 ,
There is error:while loding shared libraries:libicui18n.so.57:cannot open shared object file:No such file or directory.

I try to uninstall and reinstall wxmedit ,the same error.
I try to downgram icu to 57.1 ,it's fine.

How can i use it with icu 58.1.2 ?

**Comment by hltj** [comment]
Please rebuild wxMEdit after icu upgraded.
