### ISSUE TITLE
call to a pure virtual function

### ISSUE THREAD

**Issue by ifrh** [hltj/wxMEdit#156]
![wxmedit exe_crash_pure-virtual-function-call](https://cloud.githubusercontent.com/assets/3845055/21041922/7e8301a4-bdee-11e6-8ba2-01306f627a22.jpg)

OS version: Windows 8.1 (64bit)
wxMEdit version: v2.9.7

Sometimes I recieve Error R6025 (= call to a pure virtual function) from MS VC++ Runtime Library
caused by wxMEdit. see screenshot.

`
Calling a pure virtual function is a programming error, so you need to find the call to the pure virtual function and rewrite the code so it is not called.  
[...]
A way to find a call to a pure virtual function is to set a breakpoint on the _purecall function that is found in PureVirt.c. Breaking on this function has the advantage of keeping the stack intact so that you can trace what is occurring.`
 quoted from [https://support.microsoft.com/en-us/kb/125749](https://support.microsoft.com/en-us/kb/125749)

**Comment by hltj** [comment]
Please upgrade to latest version 3.1.
https://wxmedit.github.io/downloads.html

**Comment by ifrh** [comment]
Thanks for answer. I'll try the newer version.
