### ISSUE TITLE
Feature Advise: '\r' '\n' '\r\n' e.t.c to be displayed explicitly in text-mode.

### ISSUE THREAD

**Issue by gituser9527** [hltj/wxMEdit#159]
An 'ancient' topic about '\r'(0x0D,CR), '\n'(0x0A,LF), and '\r\n'
---
they all display in the same icon in text mode, but sometimes they should be seen easily in order to edit them in regex way, e.g replace all '\r\r' with '\r\n', or vice versa, when in a file with mixed formats of '\r' and '\n'. Notice that they are basically different:
'\r' 0x0d CR
'\n' 0x0a LF
Of course they are used as the default new-line-character when ENTER key stroked in different operating systems, and when the files are edited in another OS, if CR/LF are not displayed in their raw way, the user will get some  inconvenience.

**Comment by hltj** [comment]
No. I think you're mistaken.
Here is the icons for different newline characters:
![wxmedi_newline_icon](https://cloud.githubusercontent.com/assets/3896345/22823959/f1e69bfc-efc0-11e6-92f4-3962173104cc.png)

**Comment by gituser9527** [comment]
it's such a good implementation.
thx for noticing me, and apollogize for my inattention.
and surely this issue can be closed.

**Comment by hltj** [comment]
My pleasure :)
