### ISSUE TITLE
Centos-7: Not found the macro: 'AM_GNU_GETTEXT'  in the library

### ISSUE THREAD

**Issue by gesangtome** [hltj/wxMEdit#160]
configure.ac:14: warning: macro 'AM_GNU_GETTEXT' not found in library
I really like this software, but, Can't successfully generate configure and makefile on Centos. Can you repair it?

**Comment by gesangtome** [comment]
![2017-01-20 19-38-44](https://cloud.githubusercontent.com/assets/9876749/22148278/1e73f6b2-df48-11e6-8ab2-f701dabc3dd1.png)

**Comment by hltj** [comment]
Please install gettext-devel.
