### ISSUE TITLE
There seems to be a historical bug

### ISSUE THREAD

**Issue by catcat520** [hltj/wxMEdit#161]
在旧的 madedit 也存在

打开网络路径 \\\\192.168.1.123\test.txt

然后关闭网络路径，关闭 wxMEdit 再打开，会默认读取上次的会话，然后崩溃

---
Open a file `\\192.168.1.123\test.txt`.
Disconnect the network and restart the wxMEdit, it will load the last session and then crash.
There was the same problem with old MadEdit.

**Comment by hltj** [comment]
I will confirm later.
我晚些确认哈。

**Comment by hltj** [comment]
并不会崩溃，只是会失去响应不到一分钟，然后显示这样一个错误框：
![wxmedit_smb_err](https://user-images.githubusercontent.com/3896345/36626245-6c655ea8-196a-11e8-8b9f-9c59a1e771f8.png)

It didn't crash but popup a error dialog as the attachment snapshot after no responding less than a minite.

**Comment by hltj** [comment]
Original title: 好像一个历史悠久的 bug
