### ISSUE TITLE
连续用鼠标双击编辑内容中的任意某个单词几次，就会跳到文件尾部

### ISSUE THREAD

**Issue by lwwsw** [hltj/wxMEdit#164]
连续用鼠标双击编辑内容中的任意某个单词几次，就会跳到文件尾部。
并且从单词所在行开始一直到文件尾部，所有内容都是被选中的状态。
这个问题好像从 3.0 开始的，3.1 仍然存在。

**Comment by kappa8086** [comment]
同。这可能是个功能（三击），但实在太恼人了

**Comment by hltj** [comment]
同 #144 ，代码已修复，预计随 3.2 发布。
This is the same as #144 (fixed).
