### ISSUE TITLE
Feature request: Numbering

### ISSUE THREAD

**Issue by amirm** [hltj/wxMEdit#71]
Insert incremental numbers

Example: Using column mode, select a line in the text: (Column selection marked with "|")
foo_|,
foo_|,
foo_|,
foo_|,

Edit, Advanced, Numbering

Pop-up window will ask:
Initial number (0)
Numbering Step (1)
Numbering Step Type [Linear, Exponential]
Format [Dec, Hex, Bin, Oct]
Number of chars [Auto, 1,2,3,4,...]
Pad with [Spaces, Zero] -- Enabled only if "Number of chars" is not Auto
Align [Left, Right] -- Enabled only if "Number of chars" is not Auto AND "Pad with SPACES". Default is "Left"

EXAMPLES:

Result:
foo_000,
foo_004,
foo_008,
foo_012,
Settings for result above:
Initial number = 0
Numbering Step =4
Numbering Step Type = Linear (NextValue = PreviousValue + Step)
Format = Dec
Number of chars = 3
Pad with Zero
Align Left

Result:
1     ,
2     ,
4     ,
8     ,
16   ,
...
128 ,
256 ,
Settings for result above:
Initial number = 0
Numbering Step =2
Numbering Step Type = Exponential (NextValue = PreviousValue * Step)
Format = Dec
Number of chars = 4
Pad with Space
Align Left

Result:
    1 ,
    2 ,
    4 ,
    8 ,
   16 ,
....
  128 ,
  256 ,
Settings for result above:
Initial number = 1
Numbering Step =2
Numbering Step Type = Exponential (NextValue = PreviousValue * Step)
Format = Dec
Number of chars = 5
Pad with Space
Align Right

Result:
0001 ,
0002 ,
0004 ,
0008 ,
0010 ,
0020 ,
0040 ,
0080 ,
0100 ,
Settings for result above:
Initial number = 1
Numbering Step =2
Numbering Step Type = Exponential (NextValue = PreviousValue * Step)
Format = Hex
Number of chars = 4
Pad with Zero
Align Right

Thanks in Advance!

**Comment by amirm** [comment]
Hi, it´s me again.

If you need help with the number generator, just ask me and I´ll be glad to do it.
My idea is to have 2 functions:

void NumberGenerator_Config (int StartNumber, int Increment, int TextLength, ...);
-- It will simply copy the parameters to member variables

bool NumberGenerator_Generate(char* pDest, int MaxDestSize);
-- This function should be called every time a new number string is needed to be inserted in text
-- Result string will be put on pDest and will not exceed MaxDestSize
-- Function returns true/false if generated string had to be trimmed to not exceed MaxDestSize.
-- After generating new number, member variables are updated so that on next call, a new number string is generated i nthe sequence.

tks!

**Comment by hltj** [comment]
Hello amirm, I said complete this feature with more gain.
I had done more than you expected.
Here is simple snapshots. It's not super-cool, it's super-super-cool.

![wxmedit_ordered_sequence_en_hantfin](https://cloud.githubusercontent.com/assets/3896345/8900671/ddea4788-3474-11e5-81bd-d049f9bacb4a.png)
![wxmedit_ordered_sequence_en](https://cloud.githubusercontent.com/assets/3896345/8900672/ddf2d452-3474-11e5-901e-e9fa98dea49b.png)
![wxmedit_ordered_sequence_en_arabic](https://cloud.githubusercontent.com/assets/3896345/8900673/de8c8d18-3474-11e5-998e-3dcc175bb46e.png)
