### ISSUE TITLE
Default window size of wxMEdit/MadEdit was too small

### ISSUE THREAD

**Issue by mosir** [hltj/wxMEdit#73]
Default window size that the first time run wxMEdit/MadEdit was too small. It looks ugly.
suggest default window size to be the size of 24 line and 80 column text.
You can also consider automatically opening README.txt at the fisrt time.

original title: 第一次运行时默认窗口大小是不是应该考虑调整一下
original text:
现在第一次运行时显示的窗口大小太小了，感观上很不好。

个人建议第一次打开时把窗口文本区控制在24行80列大小，也许还可以考虑第一次运行时自动打开README.txt。

**Comment by hltj** [comment]
another feature moved to #125 .
