### ISSUE TITLE
REPLACE(CTRL+H)  >>>  issues

### ISSUE THREAD

**Issue by xsuper9988** [hltj/wxMEdit#88]
===================

EXAMPLE:
AAA
BBB
AAA
BBB
AAA
BBB

====================

i  wand  to  USE  REPLACE(CTRL+H)  chang  BBB  to  AAA...

STEP  >>>
1.Mouse  Selection  AAA   and  COPY(CTRL+C)
2.Mouse  Selection  BBB   and  RPLACE(CTRL+H)
3.1st_FIELD  =  BBB
4.MOUSE  SEL  2nd_FIELD  and  PASTE(CTRL+V)
5.2nd_FIELD  is  BBB(this  copy  is  not  step1  AAA)

if  i  Selection  words  and  use  wxMEdit   CTRL+F   or   CTRL+H
wxMEdit  will  chang  "clipboard  DATA"  to  "Selection  words"
issues  >>>  dont  chang  clipboard  DATA...thank  you  very  much...^___^

**Comment by hltj** [comment]
Confirmed.
It's side-effect by option "Auto copy the mouse-selected text to clipboard - when pressing Ctrl key".
Uncheck the options will be OK, but cannot copy selected text automatic any more either.

It will be fixed latter.
