### ISSUE TITLE
Unable to detect the file encodings correctly

### ISSUE THREAD

**Issue by yhfudev** [hltj/wxMEdit#92]
Hi,
I found that the new version of the wxmedit can't detect the file encoding correctly, due to using the ICU's charset detector functions. The ICU's charset detecting is not stable, according my test of the functions compared with that of ucharsetdetector(Mozilla's Universal Charset Detector) which was used by the old MadEdit. You may test it by using the utils/ucd in the project https://github.com/yhfudev/cpp-libucd, you may want to compile it with ICU by command line

./configure --enable-icu,

and run the command

ucd -c <files>.

I created a patch for this issue, which can be accessed by https://aur.archlinux.org/packages/wxmedit-git/. The patched version uses the enhanced version of Universal Charset Detector (libucd) which supports more languages and encodings, as well as providing thread-safe APIs for applications. You may check out the source code by https://github.com/yhfudev/cpp-libucd.

**Comment by hltj** [comment]
No. You had made a mistake.

Quite the opposite, Encoding detection ability of wxMEdit had been improved a lot after replacing old Mozilla detector with ICU detector.

I had added quite a few test cases porting from Mozilla and ICU before the refactor, see #27 , 073ed37 , d24b0a3 and de77aa6 . All these test cases from both projects were more professional designed than just grabbing from wikipedia home.

I had made much more test for detection thousands text files including source code and HTIL files with command line tools uchardet (https://github.com/BYVoid/uchardet) and icudet.py. The most results were no different for UTF-8, GBK, BIG-5 and US-ASCII files. While the results detection with icudet.py were more accurately for ISO-8859-x and Windows-125x files.

You can check out 33e75 of wxMEdit, then runs `make wxmedit_test && ./wxmedit_test`, see how many test case failures before switch to ICU detector.

You can also checkout the newest code of wxMEdit, then apply your patch and runs `make check; less test-suite.log`, see how many test case failures introduced by your patch.

**Comment by hltj** [comment]
Here is the code of icudet.py
```python
#!/usr/bin/env python
# vim: fileencoding=utf-8 sw=4 ts=4 expandtab

from __future__ import print_function
from icu import CharsetDetector
import sys

flist = [(sys.stdin, "--stdin--")]
if len(sys.argv) >= 2:
     flist = [(open(f, 'rb'), f) for f in sys.argv[1:]]

for h, f in flist:
    text = h.read()

    det = CharsetDetector()
    det.setText(text)

    if len(flist) > 1:
        print(f, "\t", end='')

    match=det.detect()
    #print 'most probable encoding'
    print(match.getName())

    if len(flist) > 1:
        continue
    print()

    matchs=det.detectAll()
    #print 'all probable encodings'
    for m in matchs:
        print(m.getName(), m.getConfidence())
```

**Comment by mirh** [comment]
Another example: files fglrx_drv.so and libfglrxdrm.so [in here](http://snapshot.debian.org/archive/debian/20160123T044910Z/pool/non-free/f/fglrx-driver/fglrx-driver_15.12-2_i386.deb)
