### ISSUE TITLE
MadEdit/wxMEdit is not responding when replace-all any Zero-Length Assertions [such as ^, $ or (?:), etc.]

### ISSUE THREAD

**Issue by qihaiyan** [hltj/wxMEdit#97]
![image](https://cloud.githubusercontent.com/assets/5896784/6072710/b16c5640-addf-11e4-858b-38dbd9d8a9d1.png)

如图所示，点击替换全部按钮后，程序就没响应了。
As shown above, click the button "Replace All" and then the editor is not responding.

**Comment by hltj** [comment]
original title: 用正则表达式替换会挂住
original text: 如图所示，点击替换全部按钮后，程序就没响应了。
